name: Auto Build

on: 
  pull_request:
    types:
    - closed
    branches:
    - main

jobs:
  build_scss:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source Git branch
        uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 10
          submodules: true

      - name: Make destination directory for compiled CSS
        run: mkdir -vp /tmp/rudolphmax.com-theme/css/

      - name: Compile CSS from SCSS files
        uses: gha-utilities/sass-build@v0.4.11
        with:
          source: css/global.scss
          destination: /tmp/rudolphmax.com-theme/css/global.css

      - name: Checkout destination Git branch
        uses: actions/checkout@v2
        with:
            ref: main
            fetch-depth: 1

      - name: Move compiled CSS to path within build branch
        run: mv /tmp/rudolphmax.com-theme/css/ css-compiled/

      - name: Add and Commit changes to main branch
        run: |
          git config --local user.email 'action@github.com'
          git config --local user.name 'GitHub Action'
          git add -f css-compiled/*
          git commit -m 'Automation : Compiled SCSS'

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT }}
          branch: main
