name: Auto Build

on: 
  push:
    branches:
    - main

jobs:
  build_scss:
    name: Build SCSS
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to deploy branch
        uses: actions/checkout@v2
        with:
          ref: deploy
          fetch-depth: 10
          submodules: true

      - name: Merge from main
        run: |
          git merge main
          git add -A
          git commit -m 'Automation : Merged from main'

      - name: Make destination directory for compiled CSS
        run: mkdir -vp /tmp/rudolphmax.com-theme/css/

      - name: Compile CSS from SCSS files
        uses: gha-utilities/sass-build@v0.4.11
        with:
          source: scss/styles.scss
          destination: /tmp/rudolphmax.com-theme/css/styles.css

      - name: Move compiled CSS to path within build branch
        run: |
          rm -rf css
          mv /tmp/rudolphmax.com-theme/css/ css/

      - name: Add and Commit changes to deploy branch
        run: |
          git config --local user.email 'action@github.com'
          git config --local user.name 'GitHub Action'
          git add -f css/*
          git commit -m 'Automation : Compiled SCSS'

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT }}
          branch: deploy
