name: PR Checks 

on: 
  pull_request:
    branches:
    - main

jobs:
  lint:
    name: Base Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_JAVASCRIPT_STANDARD: true
          VALIDATE_ALL_CODEBASE: false
          CSS_FILE_NAME: .stylelintrc.json
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  lint_twig:
    name: Lint Twig
    runs-on: ubuntu-latest
    steps:
      - name: Install Twig Lint
        run: composer global require "asm89/twig-lint" "@stable"
      
      - name: Checkout source Git branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 10
          submodules: true

      - name: Run Twig Lint
        run: ~/.composer/vendor/bin/twig-lint lint "templates/*"

  # check_scss:
  #   name: Check SCSS
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout source Git branch
  #       uses: actions/checkout@v2
  #       with:
  #         ref: ${{ github.head_ref }}
  #         fetch-depth: 10
  #         submodules: true

  #     - name: Make destination directory for compiled CSS
  #       run: mkdir -vp /tmp/rudolphmax.com-theme/css/

  #     - name: Compile CSS from SCSS files
  #       uses: gha-utilities/sass-build@v0.4.11
  #       with:
  #         source: css/global.scss
  #         destination: /tmp/rudolphmax.com-theme/css/global.css
