name: scss

on: 
  pull_request:
    branches:
    - main

jobs:
  check_scss:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source Git branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 10
          submodules: true

      - name: Make destination directory for compiled CSS
        run: mkdir -vp /tmp/rudolphmax.com-theme/css/

      - name: Compile CSS from SCSS files
        uses: gha-utilities/sass-build@v0.4.11
        with:
          source: css/global.scss
          destination: /tmp/rudolphmax.com-theme/css/global.css

  check_twig:
    runs-on: ubuntu-latest
    steps:
      - uses: php-actions/composer@v6
      
      - name: Install Twig Lint
        run: composer global require "asm89/twig-lint" "@stable"
      
      - name: Checkout source Git branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 10
          submodules: true

      - name: Run Twig Lint
        run: ~/.composer/vendor/bin/twig-lint lint templates/*